### ISSUE TITLE
Failed to install 'cordova-plugin-flurryanalytics':TypeError: Uh oh!

### ISSUE THREAD

**Issue by berndartmueller** [blakgeek/cordova-plugin-flurryanalytics#5]
Hey,

since this commit (https://github.com/blakgeek/cordova-plugin-flurryanalytics/commit/7438dc9586bcccace56690b9c4007ee7efe0c92f) I can not build my cordova project anymore. 

Does someone know how to fix this issue?

Thanks!

[39m[22m[1m[31mFailed to install 'cordova-plugin-flurryanalytics':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:139:35)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:67:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by blakgeek** [comment]
What version of Cordova and the Android platform are you using?

**Comment by berndartmueller** [comment]
cordova 4.3.0, android platform 3.7.1

**Comment by blakgeek** [comment]
Ok.  That's the issue.  The new version of the plugin is meant to work with Android platform version >= 4 where the build process uses gradle.  I'll create a separate branch that continues to support the older version and update the README with instructions.

**Comment by berndartmueller** [comment]
That's great, thank you! 

When are you finished with implementing this separate branch?

**Comment by blakgeek** [comment]
I will try to get to it by the weekend.

On Thu, Oct 8, 2015 at 1:42 PM, Bernd Artmüller notifications@github.com
wrote:

> That's great, thank you!
> 
> When are you finished with implementing this separate branch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blakgeek/cordova-plugin-flurryanalytics/issues/5#issuecomment-146634733
> .

## 

Check out my games on www.bggamecentral.com or download them from the App
Stores
https://itunes.apple.com/us/artist/henry-lawton/id895605107
[image: Get it on Google Play]
https://play.google.com/store/apps/developer?id=BG+Games

**Comment by berndartmueller** [comment]
Any news? :)

**Comment by blakgeek** [comment]
I just pushed an updated version of the plugin.xml that will work with the older android platform.  You should remove and re-add the plugin like so.  I have two removes listed because I don't which version you currently have installed

```
cordova plugins rm com.blakgeek.cordova.plugin.flurryanalytics --save
cordova plugins rm cordova-plugin-flurryanalytics --save
cordova plugins add https://github.com/blakgeek/cordova-plugin-flurryanalytics#android/3.x --save
```

**Comment by blakgeek** [comment]
Let me know if you're still running into issues.
